name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        scrope: '@chektek'
    
    - name: Install Dependencies
      run: npm install
    
    - name: Build
      run: npm run build --if-present
      
    - name: Distribute
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        npm run publish
      working-directory: ./dist
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}      
